### PR TITLE
Allow ERB in kochiku-worker.yml

### PR DESCRIPTION
**Pull request by rustygeldmacher**
Process the worker configuration file through ERB before loading it as
YAML. This allows us to, for instance, use environment variables in the
config file.

Also added some specs for the `Kochiku::Worker::Settings` class.

### CODE REVIEW

**Comment by rustygeldmacher** [comment]
@robolson -- any ideas on why the build is failing for this? I don't think my change has anything to do with the failure. Is there a way I can kick off the build again? Thanks!

**Comment by robolson** [comment]
@rustygeldmacher it looks unrelated to your change. the build is now failing on master too. I think Travis changed something.

Either way, I'll merge this as soon as I get Travis fixed. Thanks!

**Comment by rustygeldmacher** [comment]
Thanks @robolson !

**Comment by robolson** [comment]
Hi @rustygeldmacher. This looks good. Can you rebase master to fix the tests? Additionally there is now a small conflict that needs to be resolved. Once you rebase I will merge.

**Comment by robolson** [comment]
@rustygeldmacher nevermind I used the GH web interface to resolve the conflict. Thank you for the contribution!

**Comment by rustygeldmacher** [comment]
Cool, thanks for the merge @robolson !

**Pull request merged**
